<!DOCTYPE html>
<html>
<head>
    <title>Lead Assigned Notification</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <h2>New Lead Assigned to You 👤</h2>
    <p>Hello {{ $user->name }},</p>
    <p>You have been assigned to a new lead. Please review the client details below and take action:</p>
    
    <table border="0" cellpadding="5" cellspacing="0" style="width: 100%; max-width: 600px; border: 1px solid #ddd; background-color: #f9f9f9;">
        <tr>
            <td style="font-weight: bold; width: 120px;">Name:</td>
            <td>{{ $lead->name }}</td>
        </tr>
        <tr>
            <td style="font-weight: bold;">Email:</td>
            <td>{{ $lead->email }}</td>
        </tr>
        <tr>
            <td style="font-weight: bold;">Phone:</td>
            <td>{{ $lead->phone }}</td>
        </tr>
        <tr>
            <td style="font-weight: bold;">Source:</td>
            <td>{{ $lead->source ?? 'Website' }}</td>
        </tr>
        @if($lead->project)
        <tr>
            <td style="font-weight: bold;">Project:</td>
            <td>{{ $lead->project->title_en }}</td>
        </tr>
        @endif
    </table>

    @if($lead->message)
    <h3 style="margin-top: 20px;">Client Message:</h3>
    <div style="background-color: #eee; padding: 15px; border-left: 4px solid #1a365d;">
        {!! nl2br(e($lead->message)) !!}
    </div>
    @endif

    <p style="margin-top: 30px; font-size: 12px; color: #777;">
        This email was automatically generated by Crete Real Estate Platform.
    </p>
</body>
</html>
