name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('backend/.env') || copy('backend/.env.example', 'backend/.env');"

    - name: Install Dependencies
      run: cd backend && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: cd backend && php artisan key:generate

    - name: Run Migrations
      run: cd backend && php artisan migrate --env=testing
      env:
        DB_PORT: 3306
        DB_DATABASE: testing

    - name: Execute tests (Unit and Feature tests)
      run: cd backend && php artisan test --env=testing
      env:
        DB_PORT: 3306
        DB_DATABASE: testing
